### ISSUE TITLE
"sa"$USER"sa"

### ISSUE THREAD

**Issue by Ray-cmd** [Ray-cmd/minishell#70]
=================================================================
==31034==ERROR: AddressSanitizer: attempting free on address which was not malloc()-ed: 0x602000003570 in thread T0
    #0 0x562e0a65fee7 in __interceptor_free (/home/luca/Git/minishell/minishell+0xc9ee7)
    #1 0x562e0a6b5691 in dyntree_free parser/dyntree.c:98
    #2 0x562e0a6a6f7b in ctx_free_line ctx/ctx.c:106
    #3 0x562e0a6c3b0b in main /home/luca/Git/minishell/main.c:26
    #4 0x7f1ae59b3d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58
    #5 0x7f1ae59b3e3f in __libc_start_main_impl ../csu/libc-start.c:392
    #6 0x562e0a5d04e4 in _start (/home/luca/Git/minishell/minishell+0x3a4e4)

0x602000003570 is located 18 bytes to the right of 14-byte region [0x602000003550,0x60200000355e)
allocated by thread T0 here:
    #0 0x562e0a660237 in malloc (/home/luca/Git/minishell/minishell+0xca237)
    #1 0x562e0a6c4558 in ft_strdup /home/luca/Git/minishell/libft/ft_strdup.c:22
    #2 0x562e0a6b4488 in dyntree_new parser/dyntree.c:23
    #3 0x562e0a6b23fc in exctract_root parser/parser.c:64
    #4 0x562e0a6b1696 in parser parser/parser.c:25
    #5 0x562e0a6c3ce3 in main /home/luca/Git/minishell/main.c:34
    #6 0x7f1ae59b3d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: bad-free (/home/luca/Git/minishell/minishell+0xc9ee7) in __interceptor_free
==31034==ABORTING

**Comment by Ray-cmd** [comment]
Fixed with #80
