### ISSUE TITLE
ML when only pipe

### ISSUE THREAD

**Issue by Ray-cmd** [Ray-cmd/minishell#76]
```text
MiniShrek$ |
ambiguous redirect
MiniShrek$ exit

=================================================================
==25066==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 24 byte(s) in 1 object(s) allocated from:
    #0 0x555c88ca6247 in __interceptor_malloc (/home/luca/Git/minishell/minishell+0xcc247)
    #1 0x555c88cf7652 in alloc_res lexer/dyntklist_split.c:74
    #2 0x555c88cf713c in dyntklist_split lexer/dyntklist_split.c:28
    #3 0x555c88cfa388 in add_cmd_to_root parser/parser.c:139
    #4 0x555c88cf84ea in parser parser/parser.c:30
    #5 0x555c88d0be5f in main /home/luca/Git/minishell/main.c:40
    #6 0x7f59083b5d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Indirect leak of 32 byte(s) in 2 object(s) allocated from:
    #0 0x555c88ca6247 in __interceptor_malloc (/home/luca/Git/minishell/minishell+0xcc247)
    #1 0x555c88cf5c02 in dyntklist_init lexer/dyntklist.c:30
    #2 0x555c88cf7803 in alloc_res lexer/dyntklist_split.c:83
    #3 0x555c88cf713c in dyntklist_split lexer/dyntklist_split.c:28
    #4 0x555c88cfa388 in add_cmd_to_root parser/parser.c:139
    #5 0x555c88cf84ea in parser parser/parser.c:30
    #6 0x555c88d0be5f in main /home/luca/Git/minishell/main.c:40
    #7 0x7f59083b5d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

Indirect leak of 32 byte(s) in 2 object(s) allocated from:
    #0 0x555c88ca6247 in __interceptor_malloc (/home/luca/Git/minishell/minishell+0xcc247)
    #1 0x555c88cf5bd4 in dyntklist_init lexer/dyntklist.c:24
    #2 0x555c88cf7803 in alloc_res lexer/dyntklist_split.c:83
    #3 0x555c88cf713c in dyntklist_split lexer/dyntklist_split.c:28
    #4 0x555c88cfa388 in add_cmd_to_root parser/parser.c:139
    #5 0x555c88cf84ea in parser parser/parser.c:30
    #6 0x555c88d0be5f in main /home/luca/Git/minishell/main.c:40
    #7 0x7f59083b5d8f in __libc_start_call_main ../sysdeps/nptl/libc_start_call_main.h:58

SUMMARY: AddressSanitizer: 88 byte(s) leaked in 5 allocation(s).
```

**Comment by Ray-cmd** [comment]
Cannot reproduce. Its fix
